// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SortableProjectsController from "./sortable_projects_controller"
application.register("sortable-projects", SortableProjectsController)

import SortableStacksController from "./sortable_stacks_controller"
application.register("sortable-stacks", SortableStacksController)

import ToggleMenuController from "./toggle_menu_controller"
application.register("toggle-menu", ToggleMenuController)
